# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: internal.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'internal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0einternal.proto\x12\x15\x63odearena.internal.v1\"\x0f\n\rHealthRequest\"\x1c\n\x0bHealthReply\x12\r\n\x05ready\x18\x01 \x01(\x08\"\xa1\x01\n\x0bToolRequest\x12\x16\n\x0euser_public_id\x18\x01 \x01(\t\x12\x11\n\ttool_name\x18\x02 \x01(\t\x12\x13\n\x0bparams_json\x18\x03 \x01(\t\x12\x12\n\nsession_id\x18\x04 \x01(\t\x12\x12\n\nproblem_id\x18\x05 \x01(\x05\x12\x16\n\x0ehas_problem_id\x18\x06 \x01(\x08\x12\x12\n\nrequest_id\x18\x07 \x01(\t\"9\n\x0bUserRequest\x12\x16\n\x0euser_public_id\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\"P\n\x0cUsageRequest\x12\x16\n\x0euser_public_id\x18\x01 \x01(\t\x12\x14\n\x0cpayload_json\x18\x02 \x01(\t\x12\x12\n\nrequest_id\x18\x03 \x01(\t\"\x19\n\tJsonReply\x12\x0c\n\x04json\x18\x01 \x01(\t2\xe4\x02\n\x10InternalBusiness\x12Q\n\tListTools\x12\".codearena.internal.v1.UserRequest\x1a .codearena.internal.v1.JsonReply\x12S\n\x0b\x45xecuteTool\x12\".codearena.internal.v1.ToolRequest\x1a .codearena.internal.v1.JsonReply\x12R\n\nGetUserLlm\x12\".codearena.internal.v1.UserRequest\x1a .codearena.internal.v1.JsonReply\x12T\n\x0bRecordUsage\x12#.codearena.internal.v1.UsageRequest\x1a .codearena.internal.v1.JsonReply2^\n\tLlmHealth\x12Q\n\x05\x43heck\x12$.codearena.internal.v1.HealthRequest\x1a\".codearena.internal.v1.HealthReplyB(\n$com.codearena.business.internal.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'internal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.codearena.business.internal.grpcP\001'
  _globals['_HEALTHREQUEST']._serialized_start=41
  _globals['_HEALTHREQUEST']._serialized_end=56
  _globals['_HEALTHREPLY']._serialized_start=58
  _globals['_HEALTHREPLY']._serialized_end=86
  _globals['_TOOLREQUEST']._serialized_start=89
  _globals['_TOOLREQUEST']._serialized_end=250
  _globals['_USERREQUEST']._serialized_start=252
  _globals['_USERREQUEST']._serialized_end=309
  _globals['_USAGEREQUEST']._serialized_start=311
  _globals['_USAGEREQUEST']._serialized_end=391
  _globals['_JSONREPLY']._serialized_start=393
  _globals['_JSONREPLY']._serialized_end=418
  _globals['_INTERNALBUSINESS']._serialized_start=421
  _globals['_INTERNALBUSINESS']._serialized_end=777
  _globals['_LLMHEALTH']._serialized_start=779
  _globals['_LLMHEALTH']._serialized_end=873
# @@protoc_insertion_point(module_scope)
