# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app import internal_pb2 as internal__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in internal_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InternalBusinessStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTools = channel.unary_unary(
                '/codearena.internal.v1.InternalBusiness/ListTools',
                request_serializer=internal__pb2.UserRequest.SerializeToString,
                response_deserializer=internal__pb2.JsonReply.FromString,
                _registered_method=True)
        self.ExecuteTool = channel.unary_unary(
                '/codearena.internal.v1.InternalBusiness/ExecuteTool',
                request_serializer=internal__pb2.ToolRequest.SerializeToString,
                response_deserializer=internal__pb2.JsonReply.FromString,
                _registered_method=True)
        self.GetUserLlm = channel.unary_unary(
                '/codearena.internal.v1.InternalBusiness/GetUserLlm',
                request_serializer=internal__pb2.UserRequest.SerializeToString,
                response_deserializer=internal__pb2.JsonReply.FromString,
                _registered_method=True)
        self.RecordUsage = channel.unary_unary(
                '/codearena.internal.v1.InternalBusiness/RecordUsage',
                request_serializer=internal__pb2.UsageRequest.SerializeToString,
                response_deserializer=internal__pb2.JsonReply.FromString,
                _registered_method=True)


class InternalBusinessServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListTools(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserLlm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InternalBusinessServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=internal__pb2.UserRequest.FromString,
                    response_serializer=internal__pb2.JsonReply.SerializeToString,
            ),
            'ExecuteTool': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTool,
                    request_deserializer=internal__pb2.ToolRequest.FromString,
                    response_serializer=internal__pb2.JsonReply.SerializeToString,
            ),
            'GetUserLlm': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserLlm,
                    request_deserializer=internal__pb2.UserRequest.FromString,
                    response_serializer=internal__pb2.JsonReply.SerializeToString,
            ),
            'RecordUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordUsage,
                    request_deserializer=internal__pb2.UsageRequest.FromString,
                    response_serializer=internal__pb2.JsonReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'codearena.internal.v1.InternalBusiness', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('codearena.internal.v1.InternalBusiness', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InternalBusiness(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codearena.internal.v1.InternalBusiness/ListTools',
            internal__pb2.UserRequest.SerializeToString,
            internal__pb2.JsonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codearena.internal.v1.InternalBusiness/ExecuteTool',
            internal__pb2.ToolRequest.SerializeToString,
            internal__pb2.JsonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserLlm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codearena.internal.v1.InternalBusiness/GetUserLlm',
            internal__pb2.UserRequest.SerializeToString,
            internal__pb2.JsonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codearena.internal.v1.InternalBusiness/RecordUsage',
            internal__pb2.UsageRequest.SerializeToString,
            internal__pb2.JsonReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LlmHealthStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/codearena.internal.v1.LlmHealth/Check',
                request_serializer=internal__pb2.HealthRequest.SerializeToString,
                response_deserializer=internal__pb2.HealthReply.FromString,
                _registered_method=True)


class LlmHealthServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LlmHealthServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=internal__pb2.HealthRequest.FromString,
                    response_serializer=internal__pb2.HealthReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'codearena.internal.v1.LlmHealth', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('codearena.internal.v1.LlmHealth', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LlmHealth(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codearena.internal.v1.LlmHealth/Check',
            internal__pb2.HealthRequest.SerializeToString,
            internal__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
