<script setup lang="ts">
import { onMounted, ref } from "vue";
import { useRouter } from "vue-router";
import AppHeader from "@/components/AppHeader.vue";
import MetricCard from "@/components/MetricCard.vue";
import api, { clearAuth } from "@/api/client";
import { toUserMessage } from "@/utils/userMessage";
const router = useRouter(); const data = ref<Record<string, any> | null>(null); const error = ref(""); const message = ref(""); const loading = ref(true); const username = ref(""); const confirm = ref(""); const deleting = ref(false);
async function load() { try { data.value = (await api.get("/learning/archive")).data; } catch (e) { error.value = toUserMessage(e, "学习档案暂时加载不了"); } finally { loading.value = false; } }
async function download() { const result = await api.get("/learning/export"); const blob = new Blob([JSON.stringify(result.data, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "codearena-learning-export.json"; a.click(); URL.revokeObjectURL(url); }
async function emailExport() { message.value = ""; try { const result = (await api.post("/learning/export/email")).data; message.value = `已发送到 ${result.sent_to}`; } catch (e) { message.value = toUserMessage(e, "邮件发送失败"); } }
async function deleteAccount() { if (deleting.value) return; deleting.value = true; try { await api.delete("/users/me", { data: { username: username.value, confirm: confirm.value } }); clearAuth(); await router.replace("/"); } catch (e) { message.value = toUserMessage(e, "账号删除失败"); } finally { deleting.value = false; } }
onMounted(load);
</script>
<template><AppHeader title="学习档案" subtitle="你的代码、知识与复习记录由你长期拥有。"><template #actions><RouterLink class="btn-secondary report-link" to="/weekly-report">查看周报</RouterLink><button class="btn-secondary" type="button" @click="download">下载数据</button></template></AppHeader><main class="page-main narrow"><p v-if="loading" class="empty">正在整理学习档案…</p><p v-else-if="error" class="empty">{{ error }}</p><template v-else-if="data"><section class="section-card"><h2>学习数据</h2><p class="muted">提交由扩展自动写入；需要最新数据时请在仪表盘手动刷新。</p><small v-if="data.last_submission_at" class="muted">最近提交：{{ data.last_submission_at }}</small></section><div class="metrics-grid"><MetricCard label="练习提交" :value="data.summary?.submission_count || 0"/><MetricCard label="通过记录" :value="data.summary?.accepted_count || 0"/><MetricCard label="知识点" :value="data.summary?.knowledge_point_count || 0"/></div><section v-if="data.latest_nex" class="section-card"><h2>最近 Nex 总结</h2><p>{{ data.latest_nex.mastered || data.latest_nex.remaining || "本轮记录已保存。" }}</p><small class="muted">建议复习：{{ data.latest_nex.suggested_review_at }}</small></section><section v-if="data.repeated_error_problem_ids?.length" class="section-card"><h2>近期重复错误</h2><p class="muted">优先复盘题目：{{ data.repeated_error_problem_ids.join("、") }}</p></section><section class="section-card"><h2>导出</h2><p class="muted">下载完整 JSON，或在平台邮件服务配置后发送到账户邮箱。</p><button type="button" class="btn-secondary" :disabled="!data.mail_enabled" @click="emailExport">{{ data.mail_enabled ? "发送到我的邮箱" : "邮件服务尚未启用" }}</button></section><details class="section-card danger"><summary>永久删除账号</summary><p>立即清空账号、提交、知识库、复习与 Nex 数据，无法恢复。</p><label>当前用户名<input v-model="username" autocomplete="username"/></label><label>输入 DELETE 确认<input v-model="confirm" autocomplete="off"/></label><button type="button" class="danger-btn" :disabled="deleting || !username || confirm !== 'DELETE'" @click="deleteAccount">{{ deleting ? "正在删除…" : "永久删除账号" }}</button></details><p v-if="message" class="message">{{ message }}</p></template></main></template>
<style scoped>.muted,.danger p,.message{color:var(--muted)}.report-link{display:inline-flex;align-items:center;text-decoration:none}.danger{border-color:#fecaca}.danger summary{cursor:pointer;font-weight:650;color:var(--danger)}.danger label{display:block;margin:12px 0;font-size:13px}.danger input{display:block;width:100%;margin-top:5px;min-height:42px;border:1px solid var(--line);border-radius:var(--radius-sm);padding:8px 10px}.danger-btn{min-height:42px;border:0;border-radius:var(--radius-sm);padding:8px 14px;background:var(--danger);color:#fff;font:inherit;font-weight:650;cursor:pointer}.danger-btn:disabled{opacity:.45;cursor:not-allowed}</style>
